// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'filterTab': string;
  'filterTab_warning': string;
}
export const cssExports: CssExports;
export default cssExports;
