// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'header_noVulnerables': string;
  'userSection': string;
}
export const cssExports: CssExports;
export default cssExports;
